### ISSUE TITLE
Unable to Deploy to Heroku

### ISSUE THREAD

**Issue by ramisaban1** [stripe/example-terminal-backend#18]
Not sure why the app isn't able to be deployed. Take a look below:

<img width="542" alt="Screen Shot 2019-11-20 at 4 56 20 PM" src="https://user-images.githubusercontent.com/30821900/69282567-a21e3c80-0bb8-11ea-843f-6ba82cd8e445.png">

If there is anything else I can send over, let me know.

**Comment by jil-stripe** [comment]
@ramisaban1,
Thanks for reaching out and letting us know -- this certainly isn't ideal! We'll let you know when we fix the issue.
James

**Comment by ramisaban1** [comment]
Is there anything I can do to help expedite the process?

**Comment by jil-stripe** [comment]
No, but thanks for asking! I think we just fixed the issue -- could you try the deploy again and make sure?

**Comment by jil-stripe** [comment]
@ramisaban1 -- Given that we've fixed this, I'm going to close out the issue, but feel free to get back in touch if you're still having issues!
James

**Comment by ramisaban1** [comment]
Everything is working now! Thank you!
