### ISSUE TITLE
node js backend example?

### ISSUE THREAD

**Issue by marquez138** [stripe/example-terminal-backend#27]
I understand this isnt bug-related, but any chance you can push a node-based backend example instead of ruby? thanks again

**Comment by jil-stripe** [comment]
Hi @marquez138 - thanks for writing in. We'll investigate and prioritize this internally and get back to you when we publish a Node example backend.

Best,
James

**Comment by marquez138** [comment]
Thank you for the quick reply James. Can i ask if this looks right to you?  

# This endpoint creates a ConnectionToken, which gives the SDK permission
post '/connection_token' do
  validationError = validateApiKey
  if !validationError.nil?
    status 400
    return log_info(validationError)
  end

  begin
    token = Stripe::Terminal::ConnectionToken.create
  rescue Stripe::StripeError => e
    status 402
    return log_info("Error creating ConnectionToken! #{e.message}")
  end

  content_type :json
  status 200
  return {:secret => token.secret}.to_json
end


Convert to Node --------------

app.post('/connection_token', async (req, res) => {
  let connectionToken = stripe.terminal.connectionTokens.create();
  res.send(connectionToken);
});


I think i can figure out the ruby code but just need to see if im on the right path. 

thanks again - Mike

**Comment by jil-stripe** [comment]
@marquez138 - If you write into our support team at https://support.stripe.com/, they'll be able to help you with your integration code. Unfortunately, we don't have enough people looking at Github Issues to provide integration support here.

James
