### ISSUE TITLE
Error when try to deploy on heroku

### ISSUE THREAD

**Issue by malkahtani** [stripe/example-terminal-backend#28]
Please only file issues here that you believe represent actual bugs in this demo code.
If you're having general trouble with your Stripe integration, please email support@stripe.com for a faster response.
![image](https://user-images.githubusercontent.com/3840641/94597294-1116f800-0296-11eb-8119-81041bab2a96.png)

I get it is not a valid repo

**Comment by jil-stripe** [comment]
@malkahtani -
Thanks for reporting. We'll look into getting this fixed shortly.
