### ISSUE TITLE
Allowed_source_types no longer in use

### ISSUE THREAD

**Issue by flystax** [stripe/example-terminal-backend#9]
diff --git a/web.rb b/web.rb
index 5c00059..8d4c964 100644
--- a/web.rb
+++ b/web.rb
@@ -80,7 +80,7 @@ end
 post '/create_payment_intent' do
   begin
     payment_intent = Stripe::PaymentIntent.create(
-      :allowed_source_types => ['card_present'],
+      :payment_method_types => ['card_present'],
       :capture_method => 'manual',
       :amount => params[:amount],
       :currency => params[:currency] || 'usd',

**Comment by danj-stripe** [comment]
Hi @flystax,

Thanks for reporting! This should be fixed now.

Dan
